# NumPy library

* Linear Algebra Library for Python
* Main building blocks for most other libraries
* Incredable fast

> pip install numpy

#### Vectors and matrices
Vectors are strictly 1-d while matrices are 2-d (and matrices can have only one row or one column)<br>
2d -> {[[]]}<br>
1d -> {[]}<br>

### NumPY Arrays

In [1]:
my_list = [2,5,9]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([2, 5, 9])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.ones(2)

array([1., 1.])

In [19]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.linspace(0,5,2)

array([0., 5.])

In [22]:
np.eye(0,5)

array([], shape=(0, 5), dtype=float64)

In [23]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(100)

array([0.71208126, 0.20111045, 0.9142148 , 0.14996442, 0.16127223,
       0.67610893, 0.60037534, 0.4002492 , 0.63080575, 0.21571266,
       0.8843127 , 0.43223395, 0.9267511 , 0.44479236, 0.58372702,
       0.58053728, 0.83880299, 0.31217439, 0.12854498, 0.85436984,
       0.5668677 , 0.46775166, 0.99791928, 0.42499482, 0.65616465,
       0.99473163, 0.94120614, 0.67919276, 0.43361684, 0.1960944 ,
       0.09637596, 0.57624064, 0.76327609, 0.14611039, 0.85804257,
       0.74234758, 0.15677647, 0.14959379, 0.80618044, 0.77280143,
       0.22002245, 0.06551545, 0.14804465, 0.90635629, 0.94968089,
       0.12353305, 0.46890662, 0.26172233, 0.65217054, 0.12476354,
       0.37308101, 0.394202  , 0.2308266 , 0.62517903, 0.67809974,
       0.74725235, 0.21354144, 0.10067671, 0.66383735, 0.81350981,
       0.36427463, 0.26327335, 0.86001861, 0.63068496, 0.29654338,
       0.45423207, 0.70241312, 0.12391239, 0.0977859 , 0.32571888,
       0.60377298, 0.65853406, 0.07121634, 0.61872227, 0.49373

In [27]:
np.random.randn(150)

array([-1.0071765 , -0.21941013, -0.58976051, -0.22092263, -1.64649156,
        0.3974201 ,  1.5488448 ,  0.62461297,  0.33193386,  0.21526931,
       -0.21268432, -0.60512467, -0.05635177, -1.32259807,  0.04297358,
        0.59138606,  0.38385341,  0.13797116, -0.65320811,  0.5564653 ,
       -1.64394449, -3.13109969,  0.0865787 ,  0.27560982, -0.10533849,
        2.07977668, -1.86956021, -0.15639066, -1.03456275, -0.123145  ,
        1.06729752,  1.65573481,  1.18523301,  1.18361601,  0.77598983,
       -0.60933408, -1.01712534, -0.40068224,  0.22237038, -0.37400636,
        0.56460407,  0.87315796,  0.89192341,  0.79106022,  0.70141122,
        0.84510689,  0.52000434,  0.57448462,  0.74084117,  0.41323595,
       -1.54503983, -0.18734644, -0.25632679, -0.32464032, -1.52986254,
       -2.43935861,  0.46601111, -0.1028945 ,  0.30322756,  0.03205753,
       -0.62177128,  1.01034147,  1.89808659,  0.65185111, -1.46004947,
       -1.87434311,  0.45102997, -0.07983772, -1.11446581, -0.32

In [28]:
np.random.randn(5)

array([ 1.10683462, -2.09023442,  0.77011644,  1.38031651, -1.14008384])

In [35]:
np.random.randint(1,100)

2

In [43]:
np.random.randint(1,3)

2

In [44]:
np.random.randint(1,100,10)

array([89, 81, 76,  5, 12, 33, 99, 13, 36, 62])

In [46]:
arr = np.arange(100)

In [47]:
ranarr = np.random.randint(0,50,10)

In [49]:
arr.reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [51]:
ranarr.min()

5

In [52]:
ranarr.max()

46

In [54]:
ranarr.argmin()

5

In [55]:
ranarr.argmax()

1

In [58]:
arr.dtype

dtype('int64')

In [59]:
from numpy.random import randint

In [69]:
randint(5,10)

6

### NumPy indexing and Selection

In [62]:
arr = np.arange(0,11)

In [63]:
slice_of_array = arr[0:6]

In [64]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [65]:
copy = arr.copy()

In [66]:
copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
copy[:] = 100

In [68]:
copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [70]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [71]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[1][1]

25

In [73]:
arr_2d[2][1]

40

In [74]:
arr_2d[2,1]

40

In [75]:
arr_2d[1,1]

25

In [76]:
arr_2d[0,0]

5

In [77]:
arr_2d[:1,1:]

array([[10, 15]])

In [78]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [80]:
bool_arr = arr < 2

In [82]:
arr[bool_arr]

array([0, 1])

In [83]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [85]:
arr_2d = np.arange(50).reshape(5,10)

In [86]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
arr_2d[2:3,0:3]

array([[20, 21, 22]])

# Numpy Operations
* **Array with Array**
* **Array with Scalars**
* **Universal Array Function**

In [2]:
import numpy as np
arr = np.arange(0,11)

In [3]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])